name: Lint, Type Check, and Run Python Code

on:
  workflow_dispatch:
  push:

jobs:
  lint-with-ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --dev --locked

      - name: Run ruff linter
        run: uv run ruff check ./cad/

  check-with-pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --dev --locked

      - name: Run pyright
        run: uv run pyright ./cad/

  run-python-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --dev --locked

      - name: Run Python scripts in CAD folder
        run: |
          find cad/ **/cad/ -name "*.py" ! -path "*/no_ci/*" | while read file; do
            echo "Running $file"
            uv run python "$file"
          done

      - name: Compress the build folder
        run: tar -czf cad-build.tar.gz build/

      - name: Upload CAD build product to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cad-build
          path: cad-build.tar.gz
          retention-days: 2
